### ISSUE TITLE
Packaging für macOS

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/connect#17]
@murieletrentini und ich haben letzten Freitag das Packaging für macOS angeschaut. Hier das Issue dafür mit den Erkenntnissen und der Vorgehensweise. (Siehe auch #8)

## Lösungsansatz

Damit wir einfach Updates verteilen können, möchten wir die Pakete gerne über HomeBrew anbieten. Dafür müsste eine Formula in einem Git Repository ("tap") erstellt werden.

Die Formula sollte:
- [ ] Eine Abhängigkeit zu Python3 enthalten (oder ist das in den neueren macOS Versionen immer dabei?)
- [ ] Die Quelle sollte aus einem `.tar.gz`-Github-Release (welches auf ein `git tag`aufsetzt) erstellt werden.
- [ ] Das open\HSR-Paket und dependencies via `make install` installieren

Zudem wäre es elegant, die obenstehenden Schritte in einem Makefile zu automatisieren.

## Tasks
- [ ] Formula erstellen
- [ ] Tap / Git Repository anlegen
- [ ] Makefile erstellen
  - [ ] `make install`, welches mit `pip3` den Connect & Dependencies und das CUPS-Script installiert (für Aufruf aus Formula & allenfalls manuelle Installation)
  - [ ] Paketierungsprozess
- [ ] Dokumentieren von alledem

## Links
- http://formalfriday.club/2015/01/05/creating-your-own-homebrew-tap-and-formula.html

**Comment by thde** [comment]
Ich frage mich ob das system-spezifische packaging notwendig ist, wenn connect via pip verfügbar ist. Ausser bei externen Abhängigkeiten (siehe Link).

## Links
* https://github.com/Homebrew/brew/blob/master/docs/Python-for-Formula-Authors.md

**Comment by raphiz** [comment]
@thde wenn wir "nur" ein Python-Projekt ausliefern, dann würde das gehen, da hast du ganz recht. Aktuell `sync` funktioniert so einwandfrei.

Die Gründe für system-spezifische packaging sind folgende:

1. Um unsere Druckerlösung einzurichten müssen wir ein Skript verlinken und einen Daemon einrichten. Die entsprechenden Verzeichnisse und Prozeduren sind unter Linux und MacOS unterschiedlich. 
2. Updates werden über die Paketmanager garantiert häufiger gemacht als via pip :wink: 
3. Wenn Abhängigkeiten wie der python-keyring via pip installiert werden sollen,  diese aber bereits über den Paketmanager des Systems installiert wurde (oder umgekehrt), dann gibt es einen Konflikt. Das ist nebst fehlender usuability auch bad practice.

Danke für deinen Input!

**Comment by thde** [comment]
@raphiz merci für die ausführliche Antwort! Kann ich nachvollziehen.
